### ISSUE TITLE
Questions on typescript source compilation and plugin usage

### ISSUE THREAD

**Issue by pfurini** [SpoonX/aurelia-plugin-skeleton#6]
Hi
first of all thanks for this skeleton, it's more feature complete than the official aurelia one..

A couple of questions though:
- Is there a way to build `ts` files currently? I'm trying to migrate some resources that were embedded in my ts projects into independent plugins, and I'd like to avoid converting them to ES6...
- Can I use your plugin skeleton to publish new aurelia plugins to NPM? They'll be MIT licensed as well. Obviously there'll be a proper mention to your skeleton... ;)

Thanks!
P.

**Comment by doktordirk** [comment]
babel and the babel-dts-generator understand (all?) ts syntax. just rename them to js and keep writing ts i think. i made a version that uses typescript for transpiling. maybe i should finish that as well.

@RWOverdijk should we lower the license. is there any legal requirements on how it's used atm? i'd see no need for that

**Comment by pfurini** [comment]
@doktordirk There's some odd import syntax that I need in TS for some typings to work. One of them is the `extend` library.

Using `typings` I need to write the import as follows:
`import extend = require('extend');`
While in JS you should rewrite it as
`import extend from 'extend';`

Re the license, I'll keep the Spoonx copyright notice with an added _(for the original plugin skeleton)_. There will be an **acknowledgments** section in the README with a reference to this repo.

**Comment by doktordirk** [comment]
i think `import * as extend from 'extend'`or so is what's needed/used in ts. but i think that change was it.

**Comment by pfurini** [comment]
..and I use the official Microsoft coding guidelines, that prescribe the use of explicit visibility modifiers. So wherever I use `public` in my classes, babel complains about an unknown token.

> i think import \* as extend from 'extend' or so is what's needed/used in ts. but i think that change was it.

I tried that as well, but the extend module is in in `commonjs` format, and that syntax does not work with the official typings, only the node style one that I mentioned. I should rewrite the d.ts file, but I'm too lazy to do that... ;)

**Comment by pfurini** [comment]
> babel and the babel-dts-generator understand (all?) ts syntax.

Unfortunately that was a bit optimistic, I fear... I'm getting way too many errors, on things like `private`/`public` access modifiers, automatic properties in constructors, `as` declarations, etc.
I use nearly 100% of TS features, so I need a proper ts transpilation...

If your TS version is not ready yet, I could simply prepend a gulp transpilation task from ts to ES6 format. I already have a `built` folder where I put compiled tslint rules, I just need to switch the app root from `src` to `built`.

**Comment by doktordirk** [comment]
then use the aurelia-validation build. that's full ts

**Comment by pfurini** [comment]
@doktordirk You're right indeed... How many times that project has changed shape? Every time I look at it, it's been rewritten from scratch! 8-/

**Comment by doktordirk** [comment]
hehe. right. but it'S fine now. though not complete. anyways, good luck

**Comment by pfurini** [comment]
Hi, thanks for pointing me into the right direction! This is my skeleton for typescript plugins: https://github.com/nexbit/aurelia-ts-skeleton-plugin

It is based off the `aurelia/validation` structure, and it has working build, docs with `aurelia-doc` engine, and karma testing. ;)
I'll try to build my first plugin upon this skeleton, and if everything works fine, I'll write a bit of readme and spread the word on gitter... If you want to test this too, let me know what you think.
Bye!
P.
